name: OWASP Noir Security Scan

on:
  push:
    branches: ["master", "development"]
  pull_request:
    branches: ["master", "development"]

jobs:
  noir-scan:
    name: Run NOIR Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a

      - name: Run OWASP Noir
        run: |
          docker run --rm -v ${{ github.workspace }}:/app --entrypoint sh ghcr.io/owasp-noir/noir:main -c "noir -b /app -f json -o /app/endpoints.json || noir scan /app -f json -o /app/endpoints.json"

      - name: Upload endpoints.json as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: noir-endpoints
          path: endpoints.json
