name: Super-Linter Quality Assurance

on:
  push:
    branches: ["master", "development"]
  pull_request:
    branches: ["master", "development"]

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # To avoid noise, only lint files that were modified in the PR/commit
          VALIDATE_ALL_CODEBASE: false
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          MULTI_STATUS: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TSX: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JSX: false

          # You can disable specific linters if they are too noisy, for example:
          # VALIDATE_JAVASCRIPT_STANDARD: false
          # VALIDATE_TYPESCRIPT_STANDARD: false
