name: Super-Linter Quality Assurance

on:
  push:
    branches: ["master", "development"]
  pull_request:
    branches: ["master", "development"]

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: super-linter/super-linter@108536fa21a9e3c8a5b40bdd30b29d74ab699d40
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # To avoid noise, only lint files that were modified in the PR/commit
          VALIDATE_ALL_CODEBASE: false
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          MULTI_STATUS: false

          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_JSX_STANDARD: false
          VALIDATE_TSX_STANDARD: false
          VALIDATE_JAVASCRIPT_BIOME: false
          VALIDATE_TYPESCRIPT_BIOME: false
          VALIDATE_JSX_BIOME: false
          VALIDATE_TSX_BIOME: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TSX: false
          VALIDATE_JSX: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_MARKDOWN: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_SPELL_CODESPELL: false
          VALIDATE_CSS: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_JSCPD: false
          VALIDATE_TRIVY: false
          VALIDATE_CHECKOV: false

      - name: Install Node.js
        uses: actions/setup-node@db0fb3a98ed314b69026b6e8c9be26a7e2fe65a8
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Next.js Build (Linting & Typechecking)
        run: npm run build
